name: Grading workflow
on:
  repository_dispatch:
    types: ["grading"]
  workflow_dispatch:

jobs:
  grade-learner:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Grading results
        uses: GitHubActionExercise/check-secrets-action
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          feedback: ${{ toJSON(github.event.client_payload) }}
  troubleshoot-activity:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: troubleshooting steps
        run: echo "If you're stuck, this documentation may be helpful; https://docs.github.com/en/actions/reference/encrypted-secrets"
