name: Use Secrets
on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml" 

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
       -uses: actions/rammyada
       -name: Grade use-secrets activity
        id: ACTIONEXERCISE
        uses: ./.github/actions/check-secrets-action
        with:
          secrets-context: ${{ toJSON(secrets) }}
          
